//
//  InstallmentsSelectionPresenter.swift
//  PaymentApp
//
//  Created by Alejandro Melo Domínguez on 08-01-19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InstallmentsSelectionPresentationLogic {
    func presentSomething(response: InstallmentsSelection.Something.Response)
}

class InstallmentsSelectionPresenter: InstallmentsSelectionPresentationLogic {
    weak var viewController: InstallmentsSelectionDisplayLogic?

    // MARK: Do something

    func presentSomething(response: InstallmentsSelection.Something.Response) {
        let viewModel = InstallmentsSelection.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
