//
//  PaymentMethodCCPresenter.swift
//  PaymentApp
//
//  Created by Alejandro Melo Domínguez on 08-01-19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentMethodCCPresentationLogic {
    func presentLoadingIndicator(response: PaymentMethodCC.LoadPaymentMethods.Response)
    func presentPaymentMethods(response: PaymentMethodCC.LoadPaymentMethods.Response)
    func presentErrorMessage(response: PaymentMethodCC.LoadPaymentMethods.ErrorResponse)
}

class PaymentMethodCCPresenter: PaymentMethodCCPresentationLogic {
    weak var viewController: PaymentMethodCCDisplayLogic?

    // MARK: Do something
    func presentLoadingIndicator(response: PaymentMethodCC.LoadPaymentMethods.Response) {
        if response.isLoading {
            viewController?.showLoadingIndicator()
        } else {
            viewController?.hideLoadingIndicator()
        }
    }

    func presentPaymentMethods(response: PaymentMethodCC.LoadPaymentMethods.Response) {
        let paymentMethods = response.paymentMethods
        var pmViewModels: [PaymentMethodViewModel] = []

        paymentMethods.forEach {
            let pmViewModel = PaymentMethodViewModel(imageUrl: $0.thumbnail,
                                                     name: $0.name,
                                                     type: "Tarjeta de crédito")
            pmViewModels.append(pmViewModel)
        }

        let viewModel = PaymentMethodCC.LoadPaymentMethods.ViewModel(isLoading: response.isLoading,
                                                                     paymentMethods: pmViewModels)
        viewController?.displayPaymentMethods(viewModel: viewModel)
    }

    func presentErrorMessage(response: PaymentMethodCC.LoadPaymentMethods.ErrorResponse) {
        // Here we should do stuff like localize strings and format
        let viewModel = PaymentMethodCC.LoadPaymentMethods.ErrorViewModel(title: response.title,
                                                                          message: response.message,
                                                                          cancelButtonTitle: "Volver")
        viewController?.displayErrorMessage(viewModel: viewModel)
    }
}
