//
//  PaymentMethodCCPresenter.swift
//  PaymentApp
//
//  Created by Alejandro Melo Domínguez on 08-01-19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentMethodCCPresentationLogic {
    func presentSomething(response: PaymentMethodCC.Something.Response)
}

class PaymentMethodCCPresenter: PaymentMethodCCPresentationLogic {
    weak var viewController: PaymentMethodCCDisplayLogic?

    // MARK: Do something

    func presentSomething(response: PaymentMethodCC.Something.Response) {
        let viewModel = PaymentMethodCC.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
