//
//  PaymentMethodCCWorker.swift
//  PaymentApp
//
//  Created by Alejandro Melo Domínguez on 08-01-19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PaymentMethodCCWorker {
    func getPaymentMethods(completion: @escaping ((PaymentMethods?, Bool, Error?) -> Void)) {
        API().getPaymentMethods(success: { (methods) in
            completion(methods, true, nil)
        }) { (error) in
            completion(nil, false, error)
        }
    }
}
