//
//  PaymentMethodCCInteractor.swift
//  PaymentApp
//
//  Created by Alejandro Melo Domínguez on 08-01-19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentMethodCCBusinessLogic {
    func doSomething(request: PaymentMethodCC.Something.Request)
}

protocol PaymentMethodCCDataStore {
    var amount: Int? { get set }
}

class PaymentMethodCCInteractor: PaymentMethodCCBusinessLogic, PaymentMethodCCDataStore {
    var presenter: PaymentMethodCCPresentationLogic?
    var worker: PaymentMethodCCWorker?
    var amount: Int? {
        didSet {
            print("Chosen amount: \(String(describing: amount))")
        }
    }

    // MARK: Do something

    func doSomething(request: PaymentMethodCC.Something.Request) {
        worker = PaymentMethodCCWorker()
        worker?.doSomeWork()

        let response = PaymentMethodCC.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
