//
//  AmountRouter.swift
//  PaymentApp
//
//  Created by Alejandro Melo Domínguez on 07-01-19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AmountRoutingLogic {
    func routeToPaymentMethodCC(segue: UIStoryboardSegue?)
}

protocol AmountDataPassing {
    var dataStore: AmountDataStore? { get }
}

class AmountRouter: NSObject, AmountRoutingLogic, AmountDataPassing {
    weak var viewController: AmountViewController?
    var dataStore: AmountDataStore?

    // MARK: Routing

    func routeToPaymentMethodCC(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! PaymentMethodCCViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToPaymentMethodCC(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "PaymentMethodCCViewController", bundle: nil)
            let destinationVC = storyboard.instantiateInitialViewController() as! PaymentMethodCCViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToPaymentMethodCC(source: dataStore!, destination: &destinationDS)
            navigateToPaymentMethodCC(source: viewController!, destination: destinationVC)
        }

    }

    // MARK: Navigation
    func navigateToPaymentMethodCC(source: AmountViewController, destination: PaymentMethodCCViewController) {
      source.show(destination, sender: nil)
    }

    // MARK: Passing data
    func passDataToPaymentMethodCC(source: AmountDataStore, destination: inout PaymentMethodCCDataStore) {
        destination.amount = source.amount
    }
}
