//
//  AmountModels.swift
//  PaymentApp
//
//  Created by Alejandro Melo Domínguez on 07-01-19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Amount {
    // MARK: Use cases
    enum FormatAmount {
        struct Request {
            let input: String
        }

        struct Response {
            let amount: Int?
        }

        struct ViewModel {
            let formattedAmount: String?
        }
    }

    enum Something {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
