//
//  AmountPresenter.swift
//  PaymentApp
//
//  Created by Alejandro Melo Domínguez on 07-01-19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AmountPresentationLogic {
    func presentAmount(response: Amount.FormatAmount.Response)
    func clearAmount()
}

class AmountPresenter: AmountPresentationLogic {
    weak var viewController: AmountDisplayLogic?

    // MARK: Do something

    func presentAmount(response: Amount.FormatAmount.Response) {
        // Format the number

        // Update the view
        let viewModel = Amount.FormatAmount.ViewModel(formattedAmount: "$\(response.amount!)")
        viewController?.displayFormattedAmount(viewModel: viewModel)
    }

    func clearAmount() {
        viewController?.displayClearedAmount()
    }
}
