//
//  AmountInteractor.swift
//  PaymentApp
//
//  Created by Alejandro Melo Domínguez on 07-01-19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AmountBusinessLogic {
    func formatAmount(request: Amount.FormatAmount.Request)
}

protocol AmountDataStore {
    var amount: Int? { get set }
}

class AmountInteractor: AmountBusinessLogic, AmountDataStore {
    var presenter: AmountPresentationLogic?
    var worker: AmountWorker?
    var amount: Int?

    // MARK: Do something

    func formatAmount(request: Amount.FormatAmount.Request) {
        let digitSet = CharacterSet.decimalDigits
        let cleanString = String(request.input.unicodeScalars.filter { digitSet.contains($0) })

        if cleanString.isEmpty || cleanString == "0" {
            amount = 0
            presenter?.clearAmount()
        } else {
            amount = Int(cleanString)
            let response = Amount.FormatAmount.Response(amount: amount!)
            presenter?.presentAmount(response: response)
        }
    }
}
