//
//  VoucherViewController.swift
//  PaymentApp
//
//  Created by Alejandro Melo Domínguez on 1/10/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VoucherDisplayLogic: class {
    func dismissPopup()
}

class VoucherViewController: UIViewController, VoucherDisplayLogic {
    var interactor: VoucherBusinessLogic?
    var router: (NSObjectProtocol & VoucherRoutingLogic & VoucherDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = VoucherInteractor()
        let presenter = VoucherPresenter()
        let router = VoucherRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    // MARK: Use cases

    @IBAction func closePopup(_ sender: Any) {
        interactor?.didPressCloseButton()
    }

    func dismissPopup() {
        router?.dismissModalScene()
    }
}
