//
//  VoucherInteractor.swift
//  PaymentApp
//
//  Created by Alejandro Melo Domínguez on 1/10/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VoucherBusinessLogic {
    func didLoadView()
    func didPressCloseButton()
}

protocol VoucherDataStore {
    var amount: Int? { get set }
    var paymentMethod: PaymentMethod? { get set }
    var cardIssuer: Bank? { get set }
    var installment: PayerCost? { get set }
}

class VoucherInteractor: VoucherBusinessLogic, VoucherDataStore {
    var presenter: VoucherPresentationLogic?

    var amount: Int?

    var paymentMethod: PaymentMethod?
    var paymentMethodId: String? { return paymentMethod?.id }

    var cardIssuer: Bank?
    var cardIssuerId: String? { return cardIssuer?.id }

    var installment: PayerCost?

    // MARK: - Business Logic
    func didLoadView() {
        let response = Voucher.ShowData.Response(amount: amount,
                                                 paymentMethodName: paymentMethod?.name,
                                                 bank: cardIssuer?.name,
                                                 installments: installment?.recommendedMessage)
        presenter?.displayData(response: response)
    }

    func didPressCloseButton() {
        presenter?.dismissVoucher()
    }
}
