//
//  VoucherInteractor.swift
//  PaymentApp
//
//  Created by Alejandro Melo Domínguez on 1/10/19.
//  Copyright (c) 2019 Alejandro Melo Domínguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VoucherBusinessLogic {
    func didPressCloseButton()
}

protocol VoucherDataStore {

}

class VoucherInteractor: VoucherBusinessLogic, VoucherDataStore {
    var presenter: VoucherPresentationLogic?

    func didPressCloseButton() {
        presenter?.dismissVoucher()
    }
}
